# Generated by Django 5.2.7 on 2025-11-02 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'JOURNALIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='sports_newsletters', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to='news.league')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='news.league')),
            ],
            options={
                'unique_together': {('name', 'league')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'EDITOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sports_articles', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'JOURNALIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='sports_articles', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(blank=True, help_text='Optional league context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.league')),
                ('team', models.ForeignKey(blank=True, help_text='Optional team context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.team')),
            ],
        ),
    ]
